def cubo_ret(arg1, arg2, operator):
    return quad[arg1][arg2][operator]

quad = {
    'int':{
        'int':{
            '+' :'int',
            '-' :'int',
            '*' :'int',
            '/' :'int',
            '^' :'int',
            '=' :True,
            '==':'bool',
            '!=':'bool',
            '<' :'bool',
            '<=':'bool',
            '>' :'bool',
            '>=':'bool',
            '&' :'int',
            '|' :'int'
        },
        'float':{
            '+' :'float',
            '-' :'float',
            '*' :'float',
            '/' :'float',
            '^' :'float',
            '=' :False,
            '==':'bool',
            '!=':'bool',
            '<' :'bool',
            '<=':'bool',
            '>' :'bool',
            '>=':'bool',
            '&' :'float',
            '|' :'int'
        },
        'char':{
            '+' :'Error',
            '-' :'Error',
            '*' :'char',
            '/' :'Error',
            '^' :'Error',
            '=' :False,
            '==':'bool',
            '!=':'bool',
            '<' :'Error',
            '<=':'Error',
            '>' :'Error',
            '>=':'Error',
            '&' :'char',
            '|' :'int'
        },
        'bool':{
            '+' :'Error',
            '-' :'Error',
            '*' :'Error',
            '/' :'Error',
            '^' :'Error',
            '=' :False,
            '==':'bool',
            '!=':'bool',
            '<' :'Error',
            '<=':'Error',
            '>' :'Error',
            '>=':'Error',
            '&' :'Error',
            '|' :'Error'
        },
    },
    'float':{
        'int':{
            '+' :'float',
            '-' :'float',
            '*' :'float',
            '/' :'float',
            '^' :'float',
            '=' :True,
            '==':'bool',
            '!=':'bool',
            '<' :'bool',
            '<=':'bool',
            '>' :'bool',
            '>=':'bool',
            '&' :'int',
            '|' :'float'
        },
        'float':{
            '+' :'float',
            '-' :'float',
            '*' :'float',
            '/' :'float',
            '^' :'float',
            '=' :True,
            '==':'bool',
            '!=':'bool',
            '<' :'bool',
            '<=':'bool',
            '>' :'bool',
            '>=':'bool',
            '&' :'float',
            '|' :'float'
        },
        'char':{
            '+' :'Error',
            '-' :'Error',
            '*' :'Error',
            '/' :'Error',
            '^' :'Error',
            '=' :False,
            '==':'bool',
            '!=':'bool',
            '<' :'Error',
            '<=':'Error',
            '>' :'Error',
            '>=':'Error',
            '&' :'char',
            '|' :'float'
        },
        'bool':{
            '+' :'Error',
            '-' :'Error',
            '*' :'char',
            '/' :'Error',
            '^' :'Error',
            '=' :False,
            '==':'bool',
            '!=':'bool',
            '<' :'Error',
            '<=':'Error',
            '>' :'Error',
            '>=':'Error',
            '&' :'Error',
            '|' :'Error'
        },
    },
    'char':{
        'int':{
            '+' :'Error',
            '-' :'Error',
            '*' :'char',
            '/' :'Error',
            '^' :'Error',
            '=' :False,
            '==':'bool',
            '!=':'bool',
            '<' :'Error',
            '<=':'Error',
            '>' :'Error',
            '>=':'Error',
            '&' :'int',
            '|' :'char'
        },
        'float':{
            '+' :'Error',
            '-' :'Error',
            '*' :'Error',
            '/' :'Error',
            '^' :'Error',
            '=' :False,
            '==':'bool',
            '!=':'bool',
            '<' :'Error',
            '<=':'Error',
            '>' :'Error',
            '>=':'Error',
            '&' :'float',
            '|' :'char'
        },
        'char':{
            '+' :'char',
            '-' :'Error',
            '*' :'Error',
            '/' :'Error',
            '^' :'Error',
            '=' :True,
            '==':'bool',
            '!=':'bool',
            '<' :'bool',
            '<=':'bool',
            '>' :'bool',
            '>=':'bool',
            '&' :'char',
            '|' :'char'
        },
        'bool':{
            '+' :'Error',
            '-' :'Error',
            '*' :'char',
            '/' :'Error',
            '^' :'Error',
            '=' :False,
            '==':'bool',
            '!=':'bool',
            '<' :'Error',
            '<=':'Error',
            '>' :'Error',
            '>=':'Error',
            '&' :'Error',
            '|' :'Error'
        },
    },
    'bool':{
        'int':{
            '+' :'Error',
            '-' :'Error',
            '*' :'char',
            '/' :'Error',
            '^' :'Error',
            '=' :False,
            '==':'bool',
            '!=':'bool',
            '<' :'Error',
            '<=':'Error',
            '>' :'Error',
            '>=':'Error',
            '&' :'Error',
            '|' :'Error'
        },
        'float':{
            '+' :'Error',
            '-' :'Error',
            '*' :'Error',
            '/' :'Error',
            '^' :'Error',
            '=' :False,
            '==':'bool',
            '!=':'bool',
            '<' :'Error',
            '<=':'Error',
            '>' :'Error',
            '>=':'Error',
            '&' :'Error',
            '|' :'Error'
        },
        'char':{
            '+' :'char',
            '-' :'Error',
            '*' :'Error',
            '/' :'Error',
            '^' :'Error',
            '=' :False,
            '==':'bool',
            '!=':'bool',
            '<' :'Error',
            '<=':'Error',
            '>' :'Error',
            '>=':'Error',
            '&' :'Error',
            '|' :'Error'
        },
        'bool':{
            '+' :'Error',
            '-' :'Error',
            '*' :'Error',
            '/' :'Error',
            '^' :'Error',
            '=' :True,
            '==':'bool',
            '!=':'bool',
            '<' :'Error',
            '<=':'Error',
            '>' :'Error',
            '>=':'Error',
            '&' :'bool',
            '|' :'bool'
        }
    }
}

